### ISSUE TITLE
Error Generator 

### ISSUE THREAD

**Issue by MrChinnOh** [KirianCaumes/FFHB-Championship-Calendar-Generator#2]
The FFHB site has been completely redone and your tool no longer works.
<img width="1302" alt="image" src="https://github.com/KirianCaumes/FFHB-Championship-Calendar-Generator/assets/88510257/0faf4062-e32d-41f0-a0e5-0a6d93926fd5">

**Comment by KirianCaumes** [comment]
Indeed, they seems to have changed everything!

I just took a quick look, and it seems that result from API are now encrypted.

I found this part in their code responsible for decrypting API results:

```js
// https://www.ffhandball.fr/wp-content/plugins/smartfire-blocks-project-library/build/static/js/shared/utils.ts
const getBodyDataAttribute = (attributeName, defaultValue = '') => {
    const attribute = document.body.getAttribute(attributeName)
    return attribute ?? defaultValue
}

const xorDecipherBase64 = (strBase64, key) => {
    const str = window.atob(strBase64)
    let result = ''
    let key_len = key.length
    for (let i = 0; i < str.length; i++) {
        result += String.fromCharCode(str.charCodeAt(i) ^ key.charCodeAt(i % key_len))
    }
    return result
}

const xorDecipherAndParse = (str) => {
    const decodeKey = getBodyDataAttribute('data-cfk', 'nokey')
    const decodedStringifyAttributes = xorDecipherBase64(str, decodeKey)
    return JSON.parse(decodedStringifyAttributes)
}

xorDecipherAndParse('DATA FROM API HERE')
```

I will take a closer look in the next few days.

But maybe it's time for this project to end, as it seems there's a new option on FFHB website "Ajouter les matchs à votre calendrier" that generate a .ICS file.

To be continued 🕵️

**Comment by KirianCaumes** [comment]
So,

The ICS file you can download on FFHB website does not have all the informations (score, location, etc), so the project will still be alive.

I just published a new commit with stuff fixed.

Some comments:
- For some unknown reasons, referees should be in the API but the fields are always empty (same in the match details page), so for now they are no longer displayed in the generated ICS
- Address informations are no longer available in the API, and I can't find another API returning it, so I scraped this data from the match details page
- You no longer need to write you team name, as it's already pre selected via the URL field (take a look at the placeholder and help text from the URL input)
- As of now, the Handball season as ended, so maybe when the new one is going start, we will find more issues with this fix, wait and see 

Let me know if it's working for you 💁‍♂️
