### ISSUE TITLE
Failed to Install for Debian 12 

### ISSUE THREAD

**Issue by MrChinnOh** [KirianCaumes/FFHB-Championship-Calendar-Generator#3]
Hello,

I can't install your tool on a debian 12, how do I access the local url? Should Apache be used?

Thank you

<img width="643" alt="Capture d’écran 2023-09-20 à 21 07 49" src="https://github.com/KirianCaumes/FFHB-Championship-Calendar-Generator/assets/88510257/8a20ee67-eb6e-4c9f-9f25-a1032f754958">

**Comment by KirianCaumes** [comment]
Hi,
I made it a bit more clear with the latest commit: https://github.com/KirianCaumes/FFHB-Championship-Calendar-Generator/commit/413cb96e340ae68b83622ab239c237f78fc7a554.
But the thing is, once started (`npm start`), you can access it on [localhost:3000](http://localhost:3000). You can also change the port by setting the `PORT` environment variable.
Let me know if it's okay for you 😉
